### ISSUE TITLE
视频采集库NPE

### ISSUE THREAD

**Issue by ChadCSong** [AgoraIO/FaceUnity#18]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.setDisplayOrientation(int)' on a null object reference
       at io.agora.processor.video.capture.VideoCaptureCamera.updateCameraParam(VideoCaptureCamera.java:78)
       at io.agora.processor.video.capture.VideoCaptureCamera.startPreview(VideoCaptureCamera.java:5)
       at io.agora.processor.media.base.BaseVideoCapture.onDataAvailable(BaseVideoCapture.java:24)
       at io.agora.processor.media.base.BaseVideoCapture.onDataAvailable(BaseVideoCapture.java:2)
       at io.agora.processor.common.connector.SrcConnector.onDataAvailable(SrcConnector.java:18)
       at io.agora.processor.video.renderer.RenderWithSurfaceView$RenderThread.surfaceTexureAvailable(RenderWithSurfaceView.java:65)
       at io.agora.processor.video.renderer.RenderWithSurfaceView$RenderThread.access$3300(RenderWithSurfaceView.java)
       at io.agora.processor.video.renderer.RenderWithSurfaceView$RenderHandler.handleMessage(RenderWithSurfaceView.java:61)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at io.agora.processor.video.renderer.RenderWithSurfaceView$RenderThread.run(RenderWithSurfaceView.java:46)

**Comment by brianxcli** [comment]
Could you give a description that how to reoccur this error？

**Comment by ChadCSong** [comment]
这是线上收集到的crash，我们自己并没有复现。崩溃率稍高

**Comment by ChadCSong** [comment]
今天在息屏状态下复现了，可能是息屏时导致的。

**Comment by brianxcli** [comment]
好的，我们跑一下看看

**Comment by brianxcli** [comment]
@ChadCSong  master 分支更新了采集方式，再试试会不会出现类似问题。
